/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.4.1.213 */
/* Module Version: 1.2 */
/* Sun May  1 17:36:29 2016 */

/* parameterized module instance */
i2c __ (.wb_clk_i( ), .wb_rst_i( ), .wb_cyc_i( ), .wb_stb_i( ), 
    .wb_we_i( ), .wb_adr_i( ), .wb_dat_i( ), .wb_dat_o( ), .wb_ack_o( ), 
    .i2c1_scl( ), .i2c1_sda( ), .i2c1_irqo( ));
